In [1]:
import numpy as np


In [3]:
list1 = [1, 2, 3, 4, 5]
a = np.array(list1)
print(type(list1))
print(type(a))
print(list1)
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
list_a = [10, 20, 30]
list_b = [20, 30, 40]
print(np.array(list_a)+np.array(list_b))


[30 50 70]


In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b.shape

(2, 3)

In [16]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a+b)

print(a-b)

print(a*b)

print(a/b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [19]:
b = np.array([[10, 20, 30], [40, 50, 60]])
c = np.array([2, 3, 4])

b + c


b * c

array([[ 20,  60, 120],
       [ 80, 150, 240]])

In [20]:
np.zeros((100, 100))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(100, 100))

In [23]:
np.eye(4)*10

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [24]:
range(10)

range(0, 10)

In [25]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [26]:
list1:list = [i for i in range(10)]
print(list1)
print(list1[0])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0


In [31]:
a = np.linspace(0, np.pi, 11)
a

array([0.        , 0.31415927, 0.62831853, 0.9424778 , 1.25663706,
       1.57079633, 1.88495559, 2.19911486, 2.51327412, 2.82743339,
       3.14159265])

In [33]:
print(np.sin(a))

[0.00000000e+00 3.09016994e-01 5.87785252e-01 8.09016994e-01
 9.51056516e-01 1.00000000e+00 9.51056516e-01 8.09016994e-01
 5.87785252e-01 3.09016994e-01 1.22464680e-16]
